### ISSUE TITLE
Game crashes when entering space

### ISSUE THREAD

**Issue by FloppaG** [Team-Propulsive/Minecraft-Propulsive#11]
[crash-2023-07-30_19.15.31-client.txt](https://github.com/JuneDeveloper/Minecraft-Propulsive/files/12210891/crash-2023-07-30_19.15.31-client.txt)

**Comment by JustAPotota** [comment]
Always install [Indium](https://modrinth.com/mod/indium) alongside Sodium, or else you'll break mods like this.

**Comment by FloppaG** [comment]
thx
